Connection_Details:

  db_host :  'loc lhost'
  db_name : 'testdatabase'
  db_username : 'root'
  db_password : ''

smtp_settings:
  host : 'your.smtp.server.com'
  username : 'info@yourdomain.com'
  password : 'yourSMTPpassword'
  from : 'your@address.com'
